//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogadaj()
        {
            this.Kartas = new HashSet<Karta>();
        }
    
        public int ID_Dogadaja { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public System.DateTime Datum { get; set; }
        public System.TimeSpan Vrijeme_pocetka { get; set; }
        public Nullable<double> Cijena { get; set; }
        public int ID_Administratora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta> Kartas { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
