//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int ID_Karte { get; set; }
        public int ID_Dogadaja { get; set; }
        public int ID_Korisnika { get; set; }
    
        public virtual Dogadaj Dogadaj { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
