//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavijesti
    {
        public int ID_Obavijesti { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public System.DateTime Datum { get; set; }
        public int ID_Korisnika { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
