//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radno_Vrijeme
    {
        public int ID_RadnoVrijeme { get; set; }
        public string Dan_Tjedna { get; set; }
        public Nullable<System.TimeSpan> Vrijeme_Od { get; set; }
        public Nullable<System.TimeSpan> Vrijeme_Do { get; set; }
        public int ID_Korisnika { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
